routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\ProductoController;
use App\Http\Controllers\CategoriaController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', [ProductoController::class, 'homePage'])->name('productos.home_page');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function (){
    #producto
    Route::get('/productos/render-form/{producto?}', [ProductoController::class, 'renderForm'])->name('productos.render_form');
    Route::resource('productos', 'ProductoController');
    
    #categoria
    Route::get('/categorias/render-form/{categoria?}', [CategoriaController::class, 'renderForm'])->name('categorias.render_form');
    Route::get('/categorias/{categoria}/render-subcategorias-form/', [CategoriaController::class, 'renderSubCategoriasForm'])->name('categorias.render_subcategorias_form');
    Route::post('/categorias/{categoria}/asignar-subcategorias', [CategoriaController::class, 'asignarSubCategorias'])->name('categorias.asignar_subcategorias');
    Route::resource('categorias', 'CategoriaController');
});

#Front
Route::group(['prefix' => 'front'], function () {

    #producto
    Route::prefix('productos')->group(function () {
        Route::get('/', [ProductoController::class, 'homePage'])->name('front.productos.listado');
        Route::get('/{producto}', [ProductoController::class, 'detalle'])->name('front.productos.detalle');
    });

    #categoria
    Route::prefix('categorias')->group(function () {
        Route::get('/', [CategoriaController::class, 'listado'])->name('front.categorias.listado');
        Route::get('/{categoria}', [CategoriaController::class, 'detalle'])->name('front.categorias.detalle');
    });
});

Auth::routes();

app/Models/Producto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Producto extends Model
{
    /** @var string[] */
    protected $fillable = ['nombre', 'descripcion'];

    /** @return BelongsToMany  */
    public function categorias(){
        return $this->belongsToMany(Categoria::class, 'producto_categorias')->using(ProductoCategoria::class);
    }
}

app/Http/Controllers/ProductoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreProductRequest;
use App\Http\Requests\UpdateProductRequest;
use Illuminate\Http\Request;
use App\Models\Producto;
use App\Repositories\CategoriaRepository;
use App\Repositories\ProductoRepository;
use App\Traits\AppResponseManager;
use Illuminate\Contracts\Container\BindingResolutionException;
use Illuminate\View\View;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Exception;

class ProductoController extends Controller
{
    use AppResponseManager;

    /** @var ProductoRepository $productoRepository */
    protected $productoRepository;
    /** @var CategoriaRepository $categoriaRepository */
    protected $categoriaRepository;

    /**
     * @param ProductoRepository $productoRepository 
     * @param CategoriaRepository $categoriaRepository 
     * @return void 
     */
    public function __construct(ProductoRepository $productoRepository, CategoriaRepository $categoriaRepository)
    {
        $this->productoRepository = $productoRepository;
        $this->categoriaRepository = $categoriaRepository;
    }

    /**
     * @return View|Factory 
     * @throws BindingResolutionException 
     */
    public function index()
    {
        return view('admin.producto.index', [
            'productos' => $this->productoRepository->listAll(), 
            'categorias' => $this->categoriaRepository->listAll()
        ]);
    }

    /**
     * @param Request $request 
     * @param Producto $producto 
     * @return array|RedirectResponse|View|Factory|void 
     */
    public function show(Request $request, Producto $producto)
    {
        try {
            if($request->ajax()){
                return $this->successResponse($request, ['producto' => $producto]);
            }
            return view('admin.producto.detail', ['producto' => $producto]);

        } catch (Exception $exception) {
            \Log::error(__METHOD__, ['exception' => $exception]);
            return $this->errorResponse($request);
        }
    }

    /**
     * @param StoreProductRequest $request 
     * @return array|RedirectResponse|void 
     * @throws BindingResolutionException 
     */
    public function store(StoreProductRequest $request)
    {
        try {

            $this->productoRepository->create($request->only(['nombre', 'descripcion', 'categorias']));
            return $this->successResponse($request);

        } catch (Exception $exception) {
            \Log::error(__METHOD__, ['exception' => $exception]);
            return $this->errorResponse($request);
        }
    }

    /**
     * @param UpdateProductRequest $request 
     * @param Producto $producto 
     * @return array|RedirectResponse 
     * @throws BindingResolutionException 
     */
    public function update(UpdateProductRequest $request, Producto $producto)
    {
        try {
            $this->productoRepository->update($request->only(['nombre', 'descripcion', 'categorias']), $producto);
            return $this->successResponse($request);

        } catch (Exception $exception) {
            \Log::error(__METHOD__, ['exception' => $exception]);
            return $this->errorResponse($request);
        }
    }

    /**
     * @param Request $request 
     * @param Producto $producto 
     * @return array|RedirectResponse|void 
     * @throws BindingResolutionException 
     */
    public function destroy(Request $request, Producto $producto)
    {
        try {
            $producto->categorias()->sync([]);
            $producto->delete();
            return $this->successResponse($request);

        } catch (Exception $exception) {
            \Log::error(__METHOD__, ['exception' => $exception]);
            return $this->errorResponse($request);
        }
    }

    /**
     * @return View|Factory 
     * @throws BindingResolutionException 
     */
    public function homePage()
    {
        return view('front.producto.index', [
            'productos' => $this->productoRepository->listAll(), 
            'categorias' => $this->categoriaRepository->getRootCategories()
        ]);
    }

    /**
     * @param Request $request 
     * @param Producto $producto 
     * @return View|Factory|array|RedirectResponse|void 
     */
    public function detalle(Request $request, Producto $producto)
    {
        try{
            return view('front.producto.detail', ['producto' => $producto]);
        } catch (Exception $exception) {
            \Log::error(__METHOD__, ['exception' => $exception]);
            return $this->errorResponse($request);
        }
    }

    /**
     * @param Request $request 
     * @param null|Producto $producto 
     * @return array|RedirectResponse 
     * @throws BindingResolutionException 
     */
    public function renderForm(Request $request, ?Producto $producto){
        $route = 'productos.store';
        if($producto->exists){
            $route = ['productos.update', $producto];
        }

        return $this->successResponse($request, [
            'form' => view('admin.producto.form', [
                'route' => $route,
                'producto' => $producto,
                'categorias' => $this->categoriaRepository->listForDropdown('id', 'nombre')
            ])->render() 
        ]);
    }
}

resources/views/admin/producto/detail.blade.php
@extends('admin.layouts.default')

@section('page-title', $producto->nombre)

@section('content')
    @include('partials.breadcrumbs', ['breadcrumbs' => [
        'Admin',
        'Productos' => route('productos.index'),
        $producto->nombre
    ]])

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">{{ __('Producto #'.$producto->id.': ').$producto->nombre }}
                    </h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <ul class="list-group">
                                <li class="list-group-item"><strong>{{ __('Nombre:') }}</strong> {{ $producto->nombre }}</li>
                                <li class="list-group-item"><strong>{{ __('Descripción:') }}</strong> {{ $producto->descripcion }}</li>
                                <li class="list-group-item">
                                    <strong>
                                        {{ __('Categorias asociadas') }}
                                    </strong>
                                    <ul class="list-group">
                                        @foreach( $producto->categorias as $categoria )
                                            <li class="list-group-item">
                                                {!! link_to_route('front.categorias.detalle', $categoria->nombre, ['categoria' => $categoria->id],[]) !!}
                                            </li>
                                        @endforeach
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/producto/form.blade.php
<!-- Basic modal -->
<div class="modal-header bg-blue-800">
    <h5 class="modal-title">
        <i class="icon-plus22"></i>
        {{ $producto->exists ? __('Modificar Producto #'.$producto->id ) : __('Nuevo Producto') }}
    </h5>
    <button type="button" class="close" data-dismiss="modal">×</button>
</div>

{!! Form::model($producto, ['route' => $route , 'method' => 'POST', 'role' => 'form', 'id' => 'producto-form']) !!}
@if ($producto->exists)
    {!! Form::hidden('_method', 'PUT') !!}
@endif

<div class="modal-body">
    
    <div class="form-group">
        {!! Form::label('nombre', __('Nombre')) !!}
        {!! Form::text('nombre', null, ['class' => 'form-control', 'placeholder' => __('Ingrese el nombre')]) !!}
    </div>
    
    <div class="form-group">
        {!! Form::label('descripcion', __('Descripción')) !!}
        {!! Form::text('descripcion', null, ['class' => 'form-control', 'placeholder' => __('Ingrese la descripción')]) !!}
    </div>

    <div class="form-group">
        {!! Form::label('categorias', __('Categoria')) !!}
        {!! Form::select('categorias[]', $categorias, null, ['class' => 'form-control select2', 'placeholder' => 'Seleccione una opción']) !!}
    </div>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-link" data-dismiss="modal">{{ __('Cancelar') }}</button>
    <button type="submit" class="btn bg-primary">{{ __('Guardar') }}</button>
</div>

{!! Form::close() !!}
<!-- /basic modal -->

resources/views/admin/producto/index.blade.php
@extends('admin.layouts.default')

@section('page-title', __('ABM Productos'))

@section('content')
    @include('partials.breadcrumbs', ['breadcrumbs' => [
        'Admin',
        'Productos'
    ]])
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">{{ __('Productos') }}
                        <button type="button" class="btn btn-sm btn-success btn-icon render-form"><i class="icon-plus22"></i>
                            {{ __('nuevo registro') }}</button>
                    </h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>{{ __('Nombre') }}</th>
                                        <th>{{ __('Descripción') }}</th>
                                        <th>{{ __('Categoria') }}</th>
                                        <th>{{ __('Acciones') }}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if ($productos->isEmpty())
                                        <tr>
                                            <td colspan="5" class="text-center">{{ __('No hay registros para mostrar') }}</td>
                                        </tr>
                                    @endif
                                    @foreach ($productos as $producto)
                                        <tr>
                                            <td>{{ $producto->id }}</td>
                                            <td>
                                                {!! link_to_route('productos.show', $producto->nombre, ['producto' => $producto->id], []) !!}
                                            </td>
                                            <td>{{ $producto->descripcion }}</td>
                                            <td>{{ $producto->categorias->first() ? $producto->categorias->first()->nombre : __('(no definido)') }}</td>
                                            <td>
                                                <button type="button" class="btn btn-info btn-sm update-record" record-id="{{ $producto->id }}">{{ __('Editar') }}</button>
                                                <button type="button" class="btn btn-danger btn-sm delete-record" record-id="{{ $producto->id }}">{{ __('Eliminar') }}</button>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection  


@section('modals')
    @include('admin.layouts._common_modal_form')
@endsection

@section('js')
    <script src="{{ asset('plugins/jquery-validation/jquery.validate.min.js') }}"></script>
    <script>
        let renderFormUrl = '{{ route('productos.render_form') }}';
        let deleteRecordUrl = '{{ route('productos.destroy', ['producto' => ':id']) }}';

        $(document).on('click', '.render-form,.update-record', function() {
            var productoId = $(this).attr('record-id') ?? '';
            $.get(renderFormUrl + '/' + productoId).done(function(response) {
                $('#modalForm .modal-content').html(response.data.form);
                $('#modalForm').modal('show');
                formValidate();
            });
        });

        function formValidate() {
            $('#producto-form').validate({
                rules: {
                    'nombre': {
                        required: true
                    },
                    'descripcion': {
                        required: true
                    },
                    'categorias[]': {
                        required: true
                    }
                },
                messages: {
                    'nombre': {
                        required: "Ingrese el nombre"
                    },
                    'descripcion': {
                        required: "Ingrese la descripción"
                    },
                    'categorias[]': {
                        required: "Seleccione una categoria"
                    }
                },
                errorElement: 'span',
                errorPlacement: function(error, element) {
                    error.addClass('invalid-feedback');
                    element.closest('.form-group').append(error);
                },
                highlight: function(element, errorClass, validClass) {
                    $(element).addClass('is-invalid');
                },
                unhighlight: function(element, errorClass, validClass) {
                    $(element).removeClass('is-invalid');
                },
            });
        }

        $(document).on('click', '.delete-record', function(){
            var productoId = $(this).attr('record-id') ?? '';
            if(!confirm('Esta seguro que desea continuar con la operación?') || typeof productoId === 'undefined')
                return false;
                $.ajax({
                    url: deleteRecordUrl.replace(':id', productoId),
                    type: 'DELETE',
                    data: {_token: '{{ csrf_token() }}'}
                }).done(function(response){
                    if(response.error){
                        return alert(response.message);
                    }
                    location.reload();
                });

        });
    </script>
@endsection