routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\ProductoController;
use App\Http\Controllers\CategoriaController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', [ProductoController::class, 'homePage'])->name('productos.home_page');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function (){
    #producto
    Route::get('/productos/render-form/{producto?}', [ProductoController::class, 'renderForm'])->name('productos.render_form');
    Route::resource('productos', 'ProductoController');
    
    #categoria
    Route::get('/categorias/render-form/{categoria?}', [CategoriaController::class, 'renderForm'])->name('categorias.render_form');
    Route::get('/categorias/{categoria}/render-subcategorias-form/', [CategoriaController::class, 'renderSubCategoriasForm'])->name('categorias.render_subcategorias_form');
    Route::post('/categorias/{categoria}/asignar-subcategorias', [CategoriaController::class, 'asignarSubCategorias'])->name('categorias.asignar_subcategorias');
    Route::resource('categorias', 'CategoriaController');
});

#Front
Route::group(['prefix' => 'front'], function () {

    #producto
    Route::prefix('productos')->group(function () {
        Route::get('/', [ProductoController::class, 'homePage'])->name('front.productos.listado');
        Route::get('/{producto}', [ProductoController::class, 'detalle'])->name('front.productos.detalle');
    });

    #categoria
    Route::prefix('categorias')->group(function () {
        Route::get('/', [CategoriaController::class, 'listado'])->name('front.categorias.listado');
        Route::get('/{categoria}', [CategoriaController::class, 'detalle'])->name('front.categorias.detalle');
    });
});

Auth::routes();

app/Models/Categoria.php
<?php

namespace App\Models;

use App\Traits\BadgeElement;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Categoria extends Model
{   
    use BadgeElement;

    CONST ROOT_LEVEL = 1;

    /** @var string[] */
    protected $fillable = ['nombre', 'descripcion', 'nivel'];

    /** @return BelongsToMany  */
    public function productos(){
        return $this->belongsToMany(Producto::class, 'producto_categorias')->using(ProductoCategoria::class);
    }

    /** @return HasMany  */
    public function subcategorias(){
        return $this->hasMany(Categoria::class, 'parent_id');
    }

    /** @return BelongsTo  */
    public function categoriaPadre(){
        return $this->belongsTo(Categoria::class, 'parent_id');
    }

    /** @return string  */
    public function getSubcategoriasBadgesAttribute(){
        $badges = '';
        foreach($this->subcategorias as $subcategoria){
            $badges .= $this->renderBadge('primary', $subcategoria->nombre);
        }
        return $badges;
    }

}

app/Http/Controllers/CategoriaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AssignSubCategoriesRequest;
use App\Http\Requests\StoreCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use Illuminate\Http\Request;
use App\Models\Categoria;
use App\Repositories\CategoriaRepository;
use App\Traits\AppResponseManager;
use Exception;
use Illuminate\View\View;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\Container\BindingResolutionException;
use Illuminate\Http\RedirectResponse;
use Throwable;

class CategoriaController extends Controller
{
    use AppResponseManager;
    /** @var CategoriaRepository */
    protected $categoriaRepository;

    /**
     * @param CategoriaRepository $categoriaRepository 
     * @return void 
     */
    public function __construct(CategoriaRepository $categoriaRepository)
    {
        $this->categoriaRepository = $categoriaRepository;
    }

    /**
     * @return View|Factory 
     * @throws BindingResolutionException 
     */
    public function index()
    {
        return view('admin.categoria.index', ['categorias' => $this->categoriaRepository->listAll()]);
    }

    /**
     * @param StoreCategoryRequest $request 
     * @return array|RedirectResponse|void 
     * @throws BindingResolutionException 
     */
    public function store(StoreCategoryRequest $request)
    {
        try {
            $this->categoriaRepository->create($request->only(['nombre', 'descripcion', 'nivel']));
            return $this->successResponse($request);

        } catch (Exception $exception) {
            \Log::error(__METHOD__, ['exception' => $exception]);
            return $this->errorResponse($request);
        }
    }

    /**
     * @param UpdateCategoryRequest $request 
     * @param Categoria $categoria 
     * @return array|RedirectResponse|void 
     * @throws BindingResolutionException 
     */
    public function update(UpdateCategoryRequest $request, Categoria $categoria)
    {
        try {
            $this->categoriaRepository->update($request->only(['nombre', 'descripcion', 'nivel']), $categoria);
            return $this->successResponse($request);

        } catch (Exception $exception) {
            \Log::error(__METHOD__, ['exception' => $exception]);
            return $this->errorResponse($request);
        }
    }

    /**
     * @param Request $request 
     * @param Categoria $categoria 
     * @return array|RedirectResponse|void 
     * @throws BindingResolutionException 
     */
    public function destroy(Request $request, Categoria $categoria)
    {

        try {
            $categoria->productos()->sync([]);
            $categoria->delete();
            return $this->successResponse($request);

        } catch (Exception $exception) {
            \Log::error(__METHOD__, ['exception' => $exception]);
            return $this->errorResponse($request);
        }
    }

    /**
     * @return View|Factory 
     * @throws BindingResolutionException 
     */
    public function listado()
    {
        return view('front.categoria.index', ['categorias' => $this->categoriaRepository->listAll()]);
    }

    /**
     * @param Request $request 
     * @param Categoria $categoria 
     * @return View|Factory 
     * @throws BindingResolutionException 
     */
    public function detalle(Request $request, Categoria $categoria)
    {
        return view('front.categoria.detail', [
            'categoria' => $categoria, 
            'categorias' => $this->categoriaRepository->listAll() 
        ]);
    }

    /**
     * @param Request $request 
     * @param null|Categoria $categoria 
     * @return array|RedirectResponse 
     * @throws BindingResolutionException 
     */
    public function renderForm(Request $request, ?Categoria $categoria){
        $route = 'categorias.store';
        if($categoria->exists){
            $route = ['categorias.update', $categoria];
        }

        return $this->successResponse($request, [
            'form' => view('admin.categoria.form', [
                'route' => $route,
                'categoria' => $categoria,
                'niveles' => $this->categoriaRepository->getCategoryLevelDropdown(),
            ])->render() 
        ]);
    }

    /**
     * @param Request $request 
     * @param Categoria $categoria 
     * @return array|RedirectResponse 
     * @throws BindingResolutionException 
     * @throws Throwable 
     */
    public function renderSubCategoriasForm(Request $request, Categoria $categoria){
        return $this->successResponse($request, [
            'form' => view('admin.categoria.associate-subcategories-form', [
                'categorias' => $this->categoriaRepository->categoriasSeleccionables($categoria),
                'categoriasSeleccionadas' => $categoria->subcategorias()->pluck('id'),
                'categoria' => $categoria,
            ])->render() 
        ]);
    }

    /**
     * @param AssignSubCategoriesRequest $request 
     * @param Categoria $categoria 
     * @return array|RedirectResponse|void 
     * @throws BindingResolutionException 
     */
    public function asignarSubCategorias(AssignSubCategoriesRequest $request, Categoria $categoria){
        try {
            $this->categoriaRepository->asignarSubCategorias($request->only(['subcategorias']), $categoria);
            return $this->successResponse($request);

        } catch (Exception $exception) {
            \Log::error(__METHOD__, ['exception' => $exception]);
            return $this->errorResponse($request);
        }
    }
}

resources/views/admin/categoria/associate-subcategories-form.blade.php
<!-- Basic modal -->
<div class="modal-header bg-blue-800">
    <h5 class="modal-title">
        <i class="icon-plus22"></i>
        {{ __('Categoria #'.$categoria->id ) }}
    </h5>
    <button type="button" class="close" data-dismiss="modal">×</button>
</div>

{!! Form::open(['route' =>  ['categorias.asignar_subcategorias', $categoria->id], 'method' => 'POST', 'role' => 'form', 'id' => 'categoria-form']) !!}
<div class="modal-body">
    <div class="form-group">
        {!! Form::label('subcategorias', __('Descripción')) !!}
        {!! Form::select('subcategorias[]', $categorias, $categoriasSeleccionadas, ['class' => 'form-control select2', 'style' => 'width: 100%', 'multiple' => 'multiple']) !!}
        <small class="text-muted"><strong>Nota:</strong> no son seleccionables: <br>
            <ul>
                <li>la <strong>propia categoria</strong></li>
                <li>la <strong>categoria padre</strong></li>
                <li>categorias de <strong>niveles superiores</strong></li>
            </ul>
        </small>
    </div>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-link" data-dismiss="modal">{{ __('Cancelar') }}</button>
    <button type="submit" class="btn bg-primary">{{ __('Guardar') }}</button>
</div>

{!! Form::close() !!}
<!-- /basic modal -->

resources/views/admin/categoria/form.blade.php
<!-- Basic modal -->
<div class="modal-header bg-blue-800">
    <h5 class="modal-title">
        <i class="icon-plus22"></i>
        {{ $categoria->exists ? __('Modificar Categoria #'.$categoria->id ) : __('Nueva Categoria') }}
    </h5>
    <button type="button" class="close" data-dismiss="modal">×</button>
</div>

{!! Form::model($categoria, ['route' => $route , 'method' => 'POST', 'role' => 'form', 'id' => 'categoria-form']) !!}
@if ($categoria->exists)
    {!! Form::hidden('_method', 'PUT') !!}
@endif

<div class="modal-body">
    
    <div class="form-group">
        {!! Form::label('nombre', __('Nombre')) !!}
        {!! Form::text('nombre', null, ['class' => 'form-control', 'placeholder' => __('Ingrese el nombre')]) !!}
    </div>
    
    <div class="form-group">
        {!! Form::label('descripcion', __('Descripción')) !!}
        {!! Form::text('descripcion', null, ['class' => 'form-control', 'placeholder' => __('Ingrese la descripción')]) !!}
    </div>
    
    <div class="form-group">
        {!! Form::label('nivel', __('Nivel dentro de la jerarquia')) !!}
        {!! Form::select('nivel', $niveles, null, ['class' => 'form-control select2', 'placeholder' => 'Seleccione una opción', 'disabled' => $categoria->exists]) !!}
        <small>La jerarquia se tomara en cuenta de menor a mayor. Es decir, el nivel 1 es el nivel mas alto</small>
    </div>

    @if ($categoria->exists)
    <div class="form-check">
        {!! Form::checkbox('regenerar_niveles', true, null, ['id' => 'regenerar_niveles', 'class' => 'form-check-input']) !!}
        <label for="regenerar_niveles" class="form-check-label">Desea modificar el nivel de la categoria? Este cambio afectara a todas las subcategorias que dependen de esta</label>
    </div>
    @endif
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-link" data-dismiss="modal">{{ __('Cancelar') }}</button>
    <button type="submit" class="btn bg-primary">{{ __('Guardar') }}</button>
</div>

{!! Form::close() !!}
<!-- /basic modal -->

resources/views/admin/categoria/index.blade.php
@extends('admin.layouts.default')

@section('page-title', __('ABM Categorias'))

@section('content')

    @include('partials.breadcrumbs', ['breadcrumbs' => [
        'Admin',
        'Categorias'
    ]])
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">{{ __('Categorias') }}
                        <button type="button" class="btn btn-sm btn-success btn-icon render-form"><i class="icon-plus22"></i>
                            {{ __('nuevo registro') }}</button>
                    </h5>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-12">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>{{ __('Nombre') }}</th>
                                        <th>{{ __('Nivel en la Jerarquía') }}</th>
                                        <th>{{ __('Categoria Padre') }}</th>
                                        <th>{{ __('Subcategorias') }}</th>
                                        <th>{{ __('Acciones') }}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if ($categorias->isEmpty())
                                        <tr>
                                            <td colspan="6" class="text-center">{{ __('No hay registros para mostrar') }}</td>
                                        </tr>
                                    @endif

                                    @foreach ($categorias as $categoria)
                                        <tr>
                                            <td>{{ $categoria->id }}</td>
                                            <td>{{ $categoria->nombre }}</td>
                                            <td>{{ $categoria->nivel }}</td>
                                            <td>{{ $categoria->categoriaPadre ? $categoria->categoriaPadre->nombre : __('(no definido)') }}</td>
                                            <td> {!! $categoria->subcategorias_badges !!} </td>
                                            <td>
                                                <button type="button" class="btn btn-primary btn-sm asignar-subcategorias" record-id="{{ $categoria->id }}">{{ __('Asignar Subcategorias') }}</button>
                                                <button type="button" class="btn btn-info btn-sm update-record" record-id="{{ $categoria->id }}">{{ __('Editar') }}</button>
                                                <button type="button" class="btn btn-danger btn-sm delete-record" record-id="{{ $categoria->id }}">{{ __('Eliminar') }}</button>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('modals')
    @include('admin.layouts._common_modal_form')
@endsection

@section('css')
    <link href="{{ asset('plugins/select2/css/select2.min.css') }}" rel="stylesheet" type="text/css">
@endsection

@section('js')
    <script src="{{ asset('plugins/jquery-validation/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('plugins/select2/js/select2.full.min.js') }}"></script>
    <script>
        let renderFormUrl = '{{ route('categorias.render_form') }}';
        let renderSubCategoriasFormUrl = '{{ route('categorias.render_subcategorias_form', ['categoria' => ':id']) }}';
        let deleteRecordUrl = '{{ route('categorias.destroy', ['categoria' => ':id']) }}';

        $(document).on('click', '.render-form,.update-record', function() {
            var categoriaId = $(this).attr('record-id') ?? '';
            $.get(renderFormUrl + '/' + categoriaId).done(function(response) {
                $('#modalForm .modal-content').html(response.data.form);
                $('#modalForm').modal('show');
                formValidate();
            });
        });

        $(document).on('click', '.asignar-subcategorias', function() {
            var categoriaId = $(this).attr('record-id') ?? '';
            console.log(categoriaId);
            console.log(renderSubCategoriasFormUrl);
            $.get(renderSubCategoriasFormUrl.replace(':id', categoriaId)).done(function(response) {
                $('#modalForm .modal-content').html(response.data.form);
                $('#modalForm').modal('show');
                $('.select2').select2();
            });
        });

        function formValidate() {
            $('#categoria-form').validate({
                rules: {
                    'nombre': {
                        required: true
                    },
                    'nivel': {
                        required: true
                    }
                },
                messages: {
                    'nombre': {
                        required: "Ingrese el nombre"
                    },
                    'nivel': {
                        required: "Debe seleccionar una opción"
                    }
                },
                errorElement: 'span',
                errorPlacement: function(error, element) {
                    error.addClass('invalid-feedback');
                    element.closest('.form-group').append(error);
                },
                highlight: function(element, errorClass, validClass) {
                    $(element).addClass('is-invalid');
                },
                unhighlight: function(element, errorClass, validClass) {
                    $(element).removeClass('is-invalid');
                },
            });
        }

        $(document).on('click', '.delete-record', function(){
            var categoriaId = $(this).attr('record-id') ?? '';
            if(!confirm('Esta seguro que desea continuar con la operación?') || typeof categoriaId === 'undefined')
                return false;
                $.ajax({
                    url: deleteRecordUrl.replace(':id', categoriaId),
                    type: 'DELETE',
                    data: {_token: '{{ csrf_token() }}'}
                }).done(function(response){
                    if(response.error){
                        return alert(response.message);
                    }
                    location.reload();
                });

        });
    </script>
@endsection